### ISSUE TITLE
"Unit Must Be an Integer" error message

### ISSUE THREAD

**Issue by nickpagee** [condomanagement/condo-api#46]
pls see screenshot – I entered "1" in the unit number. How did I get this message when the "unit number" errror message says "Unit is not a number"? ––> SORT OF FIG'D IT OUT: there was an extra space before the number "1", so it didnt' recognize it as a number. Going to flag for David this is going to be an ongoing issue for him UX wise, will need some more robust error handling around that field as I thought I entered it right, and a novice user would not see what you see in this screenshot and think they entered anything other than a number. Also "unit must be integer" is a jargony non-human-readable term, suggest either same as the other error message "unit is not a number", AND add something like "please check to see there are no additional characters or spaces added" (or something like that) 

![image](https://user-images.githubusercontent.com/19806031/91191276-92d99b80-e6c2-11ea-8450-6bfba30f99b4.png)

**Comment by djensenius** [comment]
Will be handled with https://github.com/condomanagement/condo-web/issues/25
