### ISSUE TITLE
User does not receive confirmation email unless they enter ONLY a valid email in the "email or phone" field

### ISSUE THREAD

**Issue by nickpagee** [condomanagement/condo-api#47]
see title – I cannot get a confirmation email sent when reserving parking UNLESS I enter only a valid email address in the "Email or Phone" field. 

Here's my understanding as an objective user: when I "logged in" using my email, my assumption is that I should receive a confirmation to that email address REGARDLESS of whatever I put in the "Email or Phone" field. 3 reasons why as a user I might think this: 

> 
> 1 – even if it's not the email belonging to the person parking, that's the email that  was chosen by the resident and the person parking as "THE email" that is being used for this parking reservation, so I assume that's where the acct info is going. 
> 
> 2 – the field "Email or Phone Number" implies both that A) this is something the team at the building might need to reach me with issues, so in this event I might even give my phone number since the email might not come straight to me, and B) by stating it will take either type, it says to me this is a loosey-goosey form field and that it doesn't really matter what format I put it in. I defintely don't think "you won't get an email unless you enter only an email"
> 
> 3 – Further to #2 above, there is no validation being done on this field, –– **(I can even submit leaving this empty!)** –– so as a user I think there's no issues at all when I submit this

BUT – then I don't receive any confirmation email about the P reservation. Exacerbating this, I do not see my Parking reservations the way that I see Amenity reservations, so without that confirmation email **as a tenant / user I would have no way to confirm how long I reserved it for **

Suggestions: 

1. can the confirmation email be sent to the email used in the login regardless of what gets entered in the "Email or Phone" field? 
2. when the 'successful reservation' confirmation message appears on screen, can it say "a confirmation was sent to the email used to login" 
3. can more specific or helpful explanation be added to this field explaining it is only for the P garage attendants to reach you if needed, OR, if this is not the case, state explicitly what the user needs to do to get the confirmation message?

**Comment by djensenius** [comment]
Going to close this issue in favour of implementing #51
